### ISSUE TITLE
Tracking issue: TODO(2.0)

### ISSUE THREAD

**Issue by gregmagolan** [aspect-build/bazel-lib#198]
- [x] remove the override_local_config_platform attribute entirely
- [x] remove deprecated & unused is_windows parameter
- [x] remove deprecated exclude_prefix from copy_to_directory https://github.com/aspect-build/bazel-lib/pull/591
- [x] remove the legacy copy_to_directory_action helper
- [x] remove output_dir in expand_variables
- [x] what to do with the "Always register toolchains" bits for WORKSPACE users?
- [x] remove local_config_platform rule (principled fix landed in Bazel 6 so this is no longer needed)

Some of the above items can be located by searching for "TODO(2.0)" in the sources

**Comment by thesayyn** [comment]
note: we should also rename `expand_make_vars` into `expand` as it includes more than make vars now that expand_template supports stamping.

**Comment by alexeagle** [comment]
#593 for toolchain registration
