### ISSUE TITLE
[FR]: Add a test that confirms that the bzlmod version matches the legacy WORKSPACE version

### ISSUE THREAD

**Issue by gregmagolan** [aspect-build/bazel-lib#363]
Ported over from silo.

Related [meeting notes](https://hackmd.io/67Cl2VnGRhGH9k4HM3Kj4A).

## Goal

Ensure that the versions stay in-sync.

## Considerations

- Should we add the test to `aspect-build/bazel-lib`? 
  - Seems like a good candidate as it needs to be shared amongst multiple repos.
  - Could be useful for thid-party repos that use `bazel-lib`.

## Tasks
- [ ] Implement the test
- [ ] Roll out to repos
  - [ ] Roll out test to https://github.com/aspect-build/bazel-benchmarks
  - [ ] Roll out test to https://github.com/aspect-build/bazel-examples
  - [ ] Roll out test to https://github.com/aspect-build/bazel-lib
  - [ ] Roll out test to https://github.com/aspect-build/bazel-super-formatter
  - [ ] Roll out test to https://github.com/aspect-build/gcc-toolchain
  - [ ] Roll out test to https://github.com/aspect-build/rules_esbuild
  - [ ] Roll out test to https://github.com/aspect-build/rules_jasmine
  - [ ] Roll out test to https://github.com/aspect-build/rules_jest
  - [ ] Roll out test to https://github.com/aspect-build/rules_js
  - [ ] Roll out test to https://github.com/aspect-build/rules_rollup
  - [ ] Roll out test to https://github.com/aspect-build/rules_sol
  - [ ] Roll out test to https://github.com/aspect-build/rules_swc
  - [ ] Roll out test to https://github.com/aspect-build/rules_terser
  - [ ] Roll out test to https://github.com/aspect-build/rules_ts
  - [ ] Roll out test to https://github.com/aspect-build/rules_webpack
  - [ ] Roll out test to https://github.com/bazel-contrib/publish-to-bcr
  - [ ] Roll out test to https://github.com/bazel-contrib/rules_oci
