### ISSUE TITLE
[FR]: Configure the Renovate bot to send updates in a single PR, every 1 week

### ISSUE THREAD

**Issue by gregmagolan** [aspect-build/bazel-lib#365]
Ported over from silo.

Related [meeting notes](https://hackmd.io/67Cl2VnGRhGH9k4HM3Kj4A).

## Tasks
- [ ] Roll out config to https://github.com/aspect-build/bazel-benchmarks
- [ ] Roll out config to https://github.com/aspect-build/bazel-examples
- [ ] Roll out config to https://github.com/aspect-build/bazel-lib
- [ ] Roll out config to https://github.com/aspect-build/bazel-super-formatter
- [ ] Roll out config to https://github.com/aspect-build/docs
- [ ] Roll out config to https://github.com/aspect-build/gcc-toolchain
- [ ] Roll out config to https://github.com/aspect-build/rules_esbuild
- [ ] Roll out config to https://github.com/aspect-build/rules_jasmine
- [ ] Roll out config to https://github.com/aspect-build/rules_jest
- [ ] Roll out config to https://github.com/aspect-build/rules_js
- [ ] Roll out config to https://github.com/aspect-build/rules_rollup
- [ ] Roll out config to https://github.com/aspect-build/rules_sol
- [ ] Roll out config to https://github.com/aspect-build/rules_swc
- [ ] Roll out config to https://github.com/aspect-build/rules_terser
- [ ] Roll out config to https://github.com/aspect-build/rules_ts
- [ ] Roll out config to https://github.com/aspect-build/rules_webpack
- [ ] Roll out config to https://github.com/bazel-contrib/publish-to-bcr
- [ ] Roll out config to https://github.com/bazel-contrib/rules_oci

**Comment by alexeagle** [comment]
How important is this? Looking for issues I can close here.
